<html>
<head>
    <link rel="stylesheet" type="text/css" href="/apps/frontend/public/css/bootstrap.min.css">
    <link rel="stylesheet" href="/node_modules/angular-ui-bootstrap/dist/ui-bootstrap-csp.css">
    <link rel="stylesheet" href="/node_modules/angular-ui-switch/angular-ui-switch.min.css">
    <link rel="stylesheet" href="/node_modules/angular-loading-bar/src/loading-bar.css" type='text/css' media='all' >

    <link rel="stylesheet" href="/node_modules/ng-datepicker/src/css/ngDatepicker.css">
</head>
<body>
<form action="/login/login" method="post">
    Név:<input type="text" name="email">
    Jelszó:<input type="password" name="pass">
    <input type="submit">
</form>
<a href="/register/index">Regisztráció</a>
<div class="scripts">
    <script src="/node_modules/angular/angular.js"></script>
    <script src="/apps/frontend/public/js/jquery-3.1.1.min.js"></script>
    <script src="/apps/frontend/public/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/node_modules/ng-datepicker/src/js/ngDatepicker.min.js"></script>
    <script src="/node_modules/angular-smart-table/dist/smart-table.min.js"></script>
    <script src="/node_modules/angular-ui-switch/angular-ui-switch.min.js"></script>
    <script src="/node_modules/angular-modal-service/dst/angular-modal-service.min.js"></script>
    <script src="/node_modules/angular-ui-bootstrap/dist/ui-bootstrap.js"></script>
    <script src="/node_modules/angular-route/angular-route.js"></script>
    <script src="/frontend-scripts.js"></script>
</div>
</body>
</html>