<form action="/bekuld" method="post">
    <input type="radio" name="gender" value="male"> Férfi
    <input type="radio" name="gender" value="female"> Nő<br>
    Név: <input type="text" name="username"><br/>
    Password: <input type="password" name="pass"><br/>
    Password újra: <input type="password" name="pass2"><br/>
    email: <input type="text" name="email"><br/>
    születési időd: <input type="date" name="age"></br> <br/>
    Kit keresel:
    <select name="looking"><br/>
        <option value="male">Férfi</option>
        <option value="female">Nő</option>
    </select><br/>

    </select>
    <input type="submit">
</form>