<form action="/settings/bekuld" method="post">
    <div id="MainMenu">
        <div id="parent">
            <a href="#parent1" class="list-group-item list-group-item-success" data-toggle="collapse"
               data-parent="#MainMenu">Account beállítások</a>
                <div class="collapse" id="parent1" style="margin: 25px;">
                    Name: <input value="<?= $user->username ?>" type="text" id="username" name="username"><br>
                    E-mail: <input value="<?= $user->email ?>" type="email" id="email" name="email"><br>
                </div>

        </div>

        <div id="parent">
            <a href="#parent2" class="list-group-item list-group-item-success" data-toggle="collapse"
               data-parent="#MainMenu">Personal Settings</a>
                <div class="collapse" id="parent2" style="margin: 25px;">
                    Kor: <input value="<?= $user->bday ?>" type="date" name="bday"></br>
                    Város: <input value="<?= $user->city ?>" type="text" id="city" name="city"><br>
                    Tanulmány: <input value="<?= $user->school ?>" type="text" id="school" name="school"><br>
                    Munkahely: <input value="<?= $user->job ?>" type="text" id="job" name="job"><br>
                    Súlyod: <input value="<?= $user->weight ?>" type="text" id="weight" name="weight"><br>
                    Magasságod: <input value="<?= $user->height ?>" type="text" id="height" name="height"><br>
                    Szemed színe: <input value="<?= $user->eColor ?>" type="text" id="eColor" name="eColor"><br>
                    Hajad színe: <input value="<?= $user->hColor ?>" type="text" id="hColor" name="hColor"><br>
                    Dohányzás: <input value="<?= $user->smoking ?>" type="text" id="smoking" name="smoking"><br>
                    Testalkat: <input value="<?= $user->looklike ?>" type="text" id="looklike" name="looklike"><br>
                    Gyerek: <input value="<?= $user->hChild ?>" type="text" id="hChild" name="hChild"><br>
                </div>
        </div>
        <div id="parent">
            <a href="#parent3" class="list-group-item list-group-item-success" data-toggle="collapse"
               data-parent="#MainMenu">Looking</a>
                <div class="collapse" id="parent3" style="margin: 25px;">
                    Nemed:
                    <select name="oGender">
                            <option value="<?= $user->looking ?>"><?= $user->looking ?></option>
                    </select>
                    <select name="tol">
                        <?php for ($i = 18; $i <= 100; $i++): ?>
                            <option <?= $user->tol == $i ? 'selected' : '' ?> value="<?= $i ?>"><?= $i ?></option>
                        <?php endfor; ?>
                    </select>

                    -

                    <select name="ig">
                        <?php for ($i = 18; $i <= 100; $i++): ?>
                            <option
                                <?= $user->ig == $i ? 'selected' : '' ?> value="<?= $i ?>"><?= $i ?></option>
                        <?php endfor; ?>
                    </select>
                </div>
        </div>
    </div>
    <input type="submit" id="gomb">
</form>